Feature/terraform-task-2
yollosun/CryptoBank pull request #2
Opened 2024-01-10 06:07 UTC by yollosun

2024-01-10 06:12 UTC, yollosun commented on infra/terraform/main.tf
> +  private_ip_address = "10.0.1.254"
I started assigning IP addresses from the end because the first ones are reserved for something (10.0.1.0-10.0.1.3)

2024-01-11 06:41 UTC, yollosun commented
@mitro unfortunately access was rejected again

2024-01-11 07:20 UTC, mitro requested changes

2024-01-12 07:02 UTC, yollosun commented on infra/terraform/modules/shared-firewall/main.tf
> +    source_port_range          = "22"
I'm sorry but I can't understand the assignment logic 😭

I can't find this explanation anywhere. Many articles describe the configuration, but I can’t find an explanation

if I set the "Inbound direction" -
what will be the configuration of the current server source or destination - so that I can say that this server accepts requests for this port and this IP address

I thought that the tables should match like this
<img width="837" alt="image" src="https://github.com/yollosun/CryptoBank/assets/75416460/0b6bc731-437a-4901-ba12-53ba4bd7c07e">
![image](https://github.com/yollosun/CryptoBank/assets/75416460/a02fabb7-e79f-494b-acaa-4d2f2770f009)

2024-01-12 07:04 UTC, yollosun commented on infra/terraform/modules/shared-firewall/main.tf
> +    source_port_range          = "22"
I'm sorry but I can't understand the assignment logic 😭

I can't find this explanation anywhere. Many articles describe the configuration, but I can’t find an explanation

if I set the "Inbound direction" -
what will be the configuration of the current server source or destination - so that I can say that this server accepts requests for this port and this IP address

I thought that the tables should match like this
<img width="944" alt="image" src="https://github.com/yollosun/CryptoBank/assets/75416460/b697baf5-cb4c-4f47-814f-feb97110aef4">
![image](https://github.com/yollosun/CryptoBank/assets/75416460/0e9ae9f7-7452-45e7-9c8d-5c044a3fd8dd)

2024-01-15 05:26 UTC, mitro approved these changes

2024-01-15 05:43 UTC, merged